export const productsEcommerce = [
  {
    id: 1,
    title: "ESP32-CAM Con Cámara OV2640 - ESP32 WiFi",
    image: "assets/images/esp32-cam.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 11,
    rating: 4,
  },
  {
    id: 2,
    title: "CI 7408, 74LS08, 2uds",
    image: "assets/images/ci-7408-74ls08-2uds_600.jpeg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 5,
    rating: 3,
  },

  {
    id: 3,
    title: "Raspberry pi 3 Ordenador de una sola placa",
    image: "assets/images/raspbian.png",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 80,
    rating: 4,
  },

  {
    id: 4,
    title: "Arduino Uno",
    image: "assets/images/arduno.png",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 25,
    rating: 5,
  },

  {
    id: 5,
    title: "Digital Multimeter Voltmeter Direct Current Current",
    image: "assets/images/Digital-Multimeter.png",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 50,
    rating: 3,
  },

  {
    id: 6,
    title: "NodeMCU V2 ESP8266 WiFi",
    image: "assets/images/nodemcu-v2-esp8266-wifi.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 10,
    rating: 4,
  },

  {
    id: 7,
    title: "Diodo Led 5mm",
    image: "assets/images/diodo-led-5mm.jpg.crdownload",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 0.30,
    rating: 4,
  },
  {
    id: 8,
    title: "Protoboard Doble 1660 Puntos",
    image: "assets/images/755169502.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    price: 25,
    rating: 4,
  },
];

export const projectEcommerce = [
  {
    id: 1,
    title: "Pagina Web",
    image: "assets/images/civil.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Civil/",
    price: 100,
    rating: 4,
  },
  {
    id: 2,
    title: "Pagina Web",
    image: "assets/images/page1.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Pagina1/",
    price: 52,
    rating: 4,
  },
  {
    id: 3,
    title: "Pagina Web",
    image: "assets/images/page2.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/React2/",
    price: 100,
    rating: 4,
  },
  {
    id: 4,
    title: "Pagina Web",
    image: "assets/images/tienda.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/electrocode/",
    price: 200,
    rating: 4,
  },
  {
    id: 5,
    title: "Pagina Web",
    image: "assets/images/ejemplo.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/pruebaweb/",
    price: 25,
    rating: 4,
  },
  {
    id: 6,
    title: "Pagina Web",
    image: "assets/images/things.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/thingslearned/",
    price: 56,
    rating: 4,
  },
  {
    id: 7,
    title: "Pagina Web",
    image: "https://images01.nicepage.com/page/42/02/website-template-preview-42023.jpg",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/food/",
    price: 52,
    rating: 4,
  },
  {
    id: 8,
    title: "Pagina Web",
    image: "assets/images/screencapture-corozco6489-github-io-Bootstrap5Simple-2021-10-18-08_45_57.png",
    link: "https://github.com/corozco6489/",
    site: "https://corozco6489.github.io/Bootstrap5Simple/",
    price: 50,
    rating: 4,
  },
];

export const mobilePortfolio = [
  {
    id: 1,
    title: "GooGle Cloud",
    image: "https://images.unsplash.com/photo-1603695576504-b2b22b530965?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=DjXhDnkmuNo&feature=youtu.be",
    description: "MQTT-ESP8266",
  },
  {
    id: 2,
    title: "GooGle Cloud",
    image: "https://images.unsplash.com/photo-1604003567179-a467f97bd200?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    link: "https://github.com/Charles6489/esp8266-get",
    site: "https://www.youtube.com/watch?v=eidRBIPeYoY",
    description: "MQTT-ESP8266",
  },
  {
    id: 3,
    title: "AWS",
    image: "assets/images/img-1.jpg",
    link: "https://github.com/Charles6489/modbus_arduino_factory_io_nodered",
    site: "https://www.youtube.com/watch?v=FHhumt2GADU",
    description: "MQTT-ESP8266",
  },
];

export const designPortfolio = [
  {
    id: 1,
    title: "ChatBot",
    image: "https://images.unsplash.com/photo-1632435499152-18838be77960?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://www.youtube.com/watch?v=vqRQqrNxscw",
    site: "https://www.youtube.com/watch?v=vqRQqrNxscw",
    description: "ARDUINO - WHATSAPP",
  },
  {
    id: 2,
    title: "ChatBot",
    image: "https://images.unsplash.com/photo-1611746869696-d09bce200020?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    description: "ARDUINO - TELEGRAM",
  },
  {
    id: 3,
    title: "Modbus Comunicacion",
    image: "assets/images/img-1.jpg",
    link: "https://github.com/Charles6489/modbus_arduino_factory_io_nodered",
    site: "https://www.youtube.com/watch?v=FHhumt2GADU",
  },
];

export const contentPortfolio = [
  {
    id: 1,
    title: "Optical Character Recognition",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/daea137a-5cd3-485e-9855-ceef8b7ce951/8c87c747-d9db-4653-b2e8-893d4e4cc9b2/images/1617204293.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89654-optical-character-recognition-ocr?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "(OCR)",
  },
  {
    id: 2,
    title: "Codigos de Lineas",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/b6086d6c-2c90-4677-99c2-83b59ec84502/2c24a7ad-410a-4af9-85cd-3ee766cd9b30/images/1618269106.png",
    link: "https://www.mathworks.com/matlabcentral/fileexchange/89461-codigos-de-lineas",
    site: "https://www.youtube.com/watch?v=Ns0gigWsijE",
    description: "Matlab - Guide",
  },
  {
    id: 3,
    title: "fourier series",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/7544ce00-76bb-40dd-ae64-bdac9554629a/6e7e6cb0-aa24-47a7-a1a1-ed865e9ecee9/images/1616884439.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89471-fourier-series",
    site: "https://www.youtube.com/watch?v=A4pPMjUCpu4",
    description: "Matlab - Guide",
  },
  {
    id: 4,
    title: "Transformada de Fourier",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/0926d5af-689c-4525-970f-ddc28ce62037/e742d0c9-67cc-41df-85fd-0960e97b6e38/images/1616884683.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89476-fourier-transform",
    site: "https://www.youtube.com/watch?v=mFPzV0_ZAaU",
    description: "Matlab - Guide",
  },
  {
    id: 5,
    title: "Antena de Onda Progresiva",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/99531845-4005-4440-8ddb-0cc5104f4062/63b04383-fcaf-45a5-b662-d9ab57f3734c/images/1616882985.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89466-antena-de-onda-progresiva",
    site: "https://www.youtube.com/watch?v=PGiCUdlkhHw",
    description: "Matlab - Guide",
  },
  {
    id: 6,
    title: "SINGLE STUB SHUNT TUNING",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/742c566e-a278-4e8d-b29c-08f79fb3060a/ff2c2392-d99b-4f5a-b3e5-c6fc117f34e1/images/1616880509.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89451-single-stub-shunt-tuning",
    site: "https://www.youtube.com/watch?v=g3iBlooyHTw",
    description: "Matlab - Guide",
  },
  {
    id: 7,
    title: "SINGLE STUB SERIES TUNING",
    image: "https://la.mathworks.com/matlabcentral/mlc-downloads/downloads/a4832235-7133-4809-8081-ccfac616edcf/023bc73a-8024-4c03-be78-763983a7eefd/images/1616892993.PNG",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/89486-single-stub-series-tuning",
    site: "https://www.youtube.com/watch?v=1RVlOyMxK_k",
    description: "Matlab - Guide",
  },
  {
    id: 8,
    title: "Procesamiento de Imagenes",
    image: "https://i.ytimg.com/vi/12cHkBRj3QY/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96942-proyecto-modulaciones-digitales-aplicado-a-imagenes-matlab",
    site: "https://www.youtube.com/watch?v=12cHkBRj3QY",
    description: "Matlab - Guide",
  },
  {
    id: 9,
    title: "Log Periodic Dipole Antenna",
    image: "https://i.ytimg.com/vi/UgPA1TDpH7Q/mqdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/96872-log-periodic-antenna",
    site: "https://www.youtube.com/watch?v=eCaaMCwWpmY",
    description: "Matlab - Guide",
  },
  {
    id: 10,
    title: "Modulacion PCM",
    image: "https://i.ytimg.com/vi/2jk2lun9zBs/maxresdefault.jpg",
    link: "https://la.mathworks.com/matlabcentral/fileexchange/97107-modulacion-pcm?s_tid=srchtitle",
    site: "https://www.youtube.com/watch?v=2jk2lun9zBs",
    description: "Matlab - Guide",
  },
];
